# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_PLATFORMS: linux/amd64,linux/arm64
  APACHE_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lbbs-apache
  PHP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lbbs-php

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata (apache)
        id: meta-apache
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.APACHE_IMAGE }}
  
      - name: Extract Docker metadata (php)
        id: meta-php
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.PHP_IMAGE }}

      - name: Build and push Docker image (apache)
        id: push-apache
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKERHUB_PLATFORMS }}
          context: .
          file: ./Dockerfile/dockerfile.apache
          push: true
          provenance: true
          sbom: true
          tags: |
            ${{ env.APACHE_IMAGE }}:${{ github.ref_name }}
            ${{ env.APACHE_IMAGE }}:latest
            ${{ steps.meta-apache.outputs.tags }}
          labels: ${{ steps.meta-apache.outputs.labels }}
          cache-from: type=gha # Pull cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Push cache to GitHub Actions cache

      - name: Build and push Docker image (php)
        id: push-php
        uses: docker/build-push-action@v5
        with:
          platforms: ${{ env.DOCKERHUB_PLATFORMS }}
          context: .
          file: ./Dockerfile/dockerfile.php
          push: true
          provenance: true
          sbom: true
          tags: |
            ${{ env.PHP_IMAGE }}:${{ github.ref_name }}
            ${{ env.PHP_IMAGE }}:latest
            ${{ steps.meta-php.outputs.tags }}
          labels: ${{ steps.meta-php.outputs.labels }}
          cache-from: type=gha # Pull cache from GitHub Actions cache
          cache-to: type=gha,mode=max # Push cache to GitHub Actions cache
